name: fullscreenvideoplayer
description: Full screen video player, with convenient management tools
version: 1.0.1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  video_player: any
  flutter_spinkit: any
  flutter_svg: any
  fluttertoast: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  assets:
    - assets/
    - assets/icons/

  uses-material-design: true
