name: fullscreenvideoplayer
description:
  Full-screen video player with convenient management tools and fine-tuning video progress with use horizontal drags
version: 1.0.1
homepage: https://github.com/Leeeeerich/full_screen_video_player

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  video_player: ^0.10.9+1
  flutter_spinkit: ^4.1.2+1
  flutter_svg: ^0.17.4
  fluttertoast: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  assets:
    - assets/
    - assets/icons/

  uses-material-design: true
